"""add shifts and employee shifts

Revision ID: 913038ade754
Revises: 8333a4651466
Create Date: 2026-08-15 18:07:25.788016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913038ade754'
down_revision = '8333a4651466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('target_headcount', sa.Integer(), nullable=False),
    sa.Column('support_headcount', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_code'), 'shifts', ['code'], unique=False)
    op.create_index(op.f('ix_shifts_organization_id'), 'shifts', ['organization_id'], unique=False)
    op.create_table('employee_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('is_support', sa.Boolean(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_shifts_employee_id'), 'employee_shifts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_shifts_shift_id'), 'employee_shifts', ['shift_id'], unique=False)
    op.create_index(op.f('ix_employee_shifts_work_date'), 'employee_shifts', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_shifts_work_date'), table_name='employee_shifts')
    op.drop_index(op.f('ix_employee_shifts_shift_id'), table_name='employee_shifts')
    op.drop_index(op.f('ix_employee_shifts_employee_id'), table_name='employee_shifts')
    op.drop_table('employee_shifts')
    op.drop_index(op.f('ix_shifts_organization_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_code'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
